<a href="https://colab.research.google.com/github/Vish-bit/Python_Core/blob/data-science-python/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Provided by AI SOCIETY.
##Trainer- Sameer Nigam

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [3]:
import numpy as np
import random

#### Create an array of 10 zeros

In [3]:
print(np.zeros((1,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Create an array of 10 ones

In [4]:
print(np.ones((1,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### Create an array of 10 fives

In [12]:
arr = np.full((1,10),5)
print(f"array({arr})")

array([[5 5 5 5 5 5 5 5 5 5]])


#### Create an array of the integers from 10 to 50

In [11]:
arr = np.arange(10, 51, 1)
print(f"array({arr})")

array([10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50])


#### Create an array of all the even integers from 10 to 50

In [10]:
arr = np.arange(10, 51, 2)
print(f"array({arr})")

array([10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50])


#### Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
list3D = [[0,1,2],[3,4,5],[6,7,8]]
print(f"array({np.array(list3D)})")

array([[0 1 2]
 [3 4 5]
 [6 7 8]])


#### Create a 3x3 identity matrix

In [13]:
matrix = np.eye(3)
print(f"array({matrix})")

array([[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]])


#### Use NumPy to generate a random number between 0 and 1

In [4]:
randNum = random.random()
print(f"array({randNum})")

array(0.4636361447415325)


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [5]:
randomArr = np.random.normal(loc=0,scale=1, size=25)
print(f"array({randomArr})")

array([ 0.36216955 -0.60920253  1.53508329 -1.15215304  3.06496655 -1.90018207
 -0.79726847  0.24795915 -0.95181635  0.39955798  1.28599741 -0.73260696
 -1.40718858  2.35339128  0.9428075  -0.77307386 -0.65222783  0.20540237
  0.34344121  0.82978396 -2.92590432  1.27516939  1.1961528   0.80811906
 -1.03156609])


#### Create the following matrix:

In [6]:
matrix = np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(f"array({matrix})")

array([[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]])


#### Create an array of 20 linearly spaced points between 0 and 1:

In [7]:
matrix = np.linspace(0,1, num=20)
print(f"array({matrix})")

array([0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ])


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [9]:
matrix = np.arange(12,27).reshape(3,5)
result = matrix[:, :-1]
result

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [10]:
matrix = np.arange(2, 13, 5).reshape(3,1)
matrix

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [11]:
newArr = np.arange(21,26,1)
newArr

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [12]:
matrix = np.arange(16, 26, 1).reshape(2,5)
matrix

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [14]:
matrix = np.arange(16, 26, 1).reshape(2,5)
print(np.sum(matrix))

205


#### Get the standard deviation of the values in mat

In [15]:
matrix = np.arange(16, 26, 1).reshape(2,5)
print(np.std(matrix))

2.8722813232690143


#### Get the sum of all the columns in mat

In [16]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
colSum = np.sum(arr,axis=0)
colSum

array([12, 15, 18])

# Great Job!